apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-deployment
  labels:
    app: add
spec:
  selector:
    matchLabels:
      app: add
  replicas: 2
  template:
    metadata:
      labels:
        app: add
    spec:
      containers:
      - name: add
        image: tanjunchen/add-service:v1.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: add-service
          containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: add-service
spec:
  selector:
    app: add
  ports:
    - port: 3000
      targetPort: add-service
